title: "theGrove\U0001F333Genius-Garage"
description: 'Genius-Garage: The place where you get support for your Mac or iDevice.'
social_link: t.me/guys_from_Cupertino
social_username: Genius
github_repo: DmytroOnopa
github_username: theGrove
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /thegrove-garage
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
